dist: bionic

language: cpp
compiler: gcc

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
    - eval "${MATRIX_EVAL}"

install:
  - sudo apt-get install libglfw3-dev
  - sudo apt-get install mesa-utils
  - sudo apt-get install freeglut3-dev

script:
  - cd build
#  - cmake -DCMAKE_BUILD_TYPE=Release ..
#  - make
  - cd ../test
  - cmake -DBUILD_TESTS=ON ..
  - make
  - ./unitTests
